const CONNECTIVITY_MODULE_URL = 'connectivity/v0';
export default {
	CONNECTIVITY_MODULE_URL: CONNECTIVITY_MODULE_URL,
	CONNECTIVITY_DETECT_URL: CONNECTIVITY_MODULE_URL + '/detect',
	CONNECTIVITY_STATUS_URL: CONNECTIVITY_MODULE_URL + '/status',

	CONNECTIVITY_MESSAGE: 'connectivity_message',
	CONNECTIVITY_STARTED: 'connectivity_started',
	CONNECTIVITY_FINISHED: 'connectivity_finished',
}
;
