const FAVORITE_DIRECTORY_MODULE_URL = 'favorite_directories/v0';
export default {
	FAVORITE_DIRECTORY_MODULE_URL: FAVORITE_DIRECTORY_MODULE_URL,
	FAVORITE_DIRECTORIES_URL: FAVORITE_DIRECTORY_MODULE_URL + '/directories'
}