const FAVORITE_HUB_MODULE_URL = 'favorite_hubs/v0';
export default {
	FAVORITE_HUB_MODULE_URL: FAVORITE_HUB_MODULE_URL,
	FAVORITE_HUB_URL: FAVORITE_HUB_MODULE_URL + '/hub',
	STATISTICS: 'statistics',

	StateEnum: {
		STATE_DISCONNECTED: 0,
		STATE_CONNECTING: 1,
		STATE_CONNECTED: 2
	},
};
