const FILESYSTEM_MODULE_URL = 'filesystem/v0';
export default {
	FILESYSTEM_MODULE_URL: FILESYSTEM_MODULE_URL,
	FILESYSTEM_LIST_URL: FILESYSTEM_MODULE_URL + '/list_items',
	FILESYSTEM_DIRECTORY_URL: FILESYSTEM_MODULE_URL + '/directory'
}