var QUEUE_MODULE_URL = 'queue/v0';
export default {
  QUEUE_MODULE_URL: QUEUE_MODULE_URL,
  BUNDLES_URL: QUEUE_MODULE_URL + '/bundles',
  BUNDLE_URL: QUEUE_MODULE_URL + '/bundle',

  BUNDLE_ADDED: 'BUNDLE_ADDED',
  BUNDLE_REMOVED: 'BUNDLE_REMOVED',
  BUNDLE_UPDATED: 'BUNDLE_UPDATED',
  BUNDLES_GET: 'BUNDLES_GET',
}
