const SETTING_MODULE_URL = 'settings/v0';
export default {
	SETTING_MODULE_URL: SETTING_MODULE_URL,
	SETTING_ITEMS_URL: SETTING_MODULE_URL + '/items',

	SettingProfileEnum: {
		PROFILE_NORMAL: 0, 
		PROFILE_RAR: 1, 
		PROFILE_LAN: 2
	},

	ConnectionModeEnum: {
		INCOMING_DISABLED: -1, 
		INCOMING_ACTIVE: 0, 
		INCOMING_ACTIVE_UPNP: 1,
		INCOMING_PASSIVE: 2,
	},
}
;
