const SHARE_MODULE_URL = 'share/v0';
export default {
	SHARE_MODULE_URL: SHARE_MODULE_URL,

	SHARE_DUPE_PATHS_URL: SHARE_MODULE_URL + '/find_dupe_paths',
	GROUPED_ROOTS_GET_URL: SHARE_MODULE_URL + '/grouped_root_paths',
	SHARE_STATS_URL: SHARE_MODULE_URL + '/stats',

	SHARE_REFRESH_URL: SHARE_MODULE_URL + '/refresh',
	SHARE_REFRESH_PATHS_URL: SHARE_MODULE_URL + '/refresh/paths',
}
;
