const SHARE_MODULE_URL = 'share/v0';
export default {
  SHARE_MODULE_URL: SHARE_MODULE_URL,
  PROFILES_GET_URL: SHARE_MODULE_URL + '/profiles',

  SHARE_DUPE_PATHS_URL: SHARE_MODULE_URL + '/find_dupe_paths',
  ROOTS_GET_URL: SHARE_MODULE_URL + '/roots',

  HIDDEN_PROFILE_ID: 1
}